# Utiliser une image Python officielle
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY metrics_collector.py requirements.txt ./

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port pour Prometheus
EXPOSE 8001

# Lancer le script Python
CMD ["python", "metrics_collector.py"]
