# =====================================
# Prometheus Configuration
# =====================================

global:
  scrape_interval: 15s        # Fréquence globale de collecte
  evaluation_interval: 15s    # Fréquence d'évaluation des règles

# =====================================
# Alerting
# =====================================
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Adresse du service Alertmanager

# =====================================
# Règles d'alerte
# =====================================
rule_files:
  - "alert_rules.yml"  # Fichier séparé contenant les règles SLA / erreurs

# =====================================
# Cibles à monitorer
# =====================================
scrape_configs:
  # -----------------------------
  # APIs FastAPI / Flask
  # -----------------------------
  - job_name: 'api_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['api_service:8000']  # Remplacer par l'adresse de ton API

  # -----------------------------
  # Exporter modèle ML (drift)
  # -----------------------------
  - job_name: 'ml_model'
    metrics_path: /metrics
    static_configs:
      - targets: ['model_exporter:9101']  # Exporter métriques ML drift/accuracy

  # -----------------------------
  # Node Exporter (système)
  # -----------------------------
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # CPU, mémoire, disque, etc.
